##################################################
################ General Settings ################
##################################################

GeneralSettings:
  botToken: "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"

  noPermissionERROR: "You Have No Permission."
  helpBlockFooter: "Server Name"

  # Can pass permission limit
  botOwnerID:
    - "286467027705790464" # WavJaby#3673
    - "810822763601461318" # XinShou#0404
    - "270062130470846465" # XinShou#8787
    - "308721713066147840" # 阿正#6176
    - "860182127798124594" # XinShou#1699

  # watching / listening / playing / competing / streaming
  activityMessage:
    - "watching;Server Name"
    - "playing;Cat❤Dog"
    - "playing;Mama❤XinShou"
  folder:
    channelLogFolder: "channelLog"
    configFolder: "configFolder"
    levelFolder: "levelFolder"

  # Youtube API KEY (https:// console.cloud.google.com/apis/)
  apiKey: "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"

  # Will send command used message to console.
  debugMode: true


##################################################
################## ID Settings ###################
##################################################

IDSettings:
  guildID: "000000000000000000"
  logChannelID: "000000000000000000"
  authChannelID: "000000000000000000"
  consoleChannelID: "000000000000000000"
  informationChannelID: "000000000000000000"

  botRoleID: "000000000000000000"
  logRoleID: "000000000000000000"
  memberRoleID: "000000000000000000"
  boostedRoleID: "000000000000000000"
  internalRoleID: "000000000000000000"

  adminPermissionID: "000000000000000000"

  # When member join the server will get role(s).
  joinRoleID:
    - "000000000000000000"
    - "000000000000000000"
    - "000000000000000000"
    - "000000000000000000"

  # When member pass the auth can get role(s).
  confirmRoleID:
    - "000000000000000000"
    - "000000000000000000"


##################################################
################ Rooms Settings ##################
##################################################

RoomSettings:
  defaultRoomName: "《🔊》%name% Room"
  defaultRoomChatName: "《📄》%name% TextChannel"
  defaultRoomBitrate: 128000

  roomCategoryID:
    - "000000000000000000"
    - "000000000000000000"


##################################################
############## Services Settings #################
##################################################

ServiceSettings:
  newServiceName: "《❗》%name% Service"
  defaultServiceMessage: "Hello %reporter%! Please Type You Problems, Admin Will Solve In A Few Minute."

  serviceCategoryID:
    - "000000000000000000"
    - "000000000000000000"

  serviceTagRoleID:
    - "000000000000000000"
    - "000000000000000000"
    - "000000000000000000"


##################################################
################### MutiBot ######################
##################################################

MultiBot:
  tokens:
    - "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"
    - "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"
    - "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"
    - "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"
    - "Forgez87MineCraftTWavJaby.love_a4.IceXinShouFebricAPI87Spigot"

  randomBot: true