##################################################
################ General Settings ################
##################################################

GeneralSettings:
  botToken: "NTc2NzQ3NDM1NjUzNTk1MTM2.XNa_6A.NQVX3VkyrfoNtCcilzmS0Spjfig"

  noPermissionERROR: "你並沒有權限執行此動作, 請保持良民以捍衛自身權益"
  helpBlockFooter: "原之序 | ORDERLY SERVER"

  folder:
    channelLogFolder: "channelLog"
    configFolder: "configFolder"
    levelFolder: "levelFolder"

  # Can pass permission limit
  botOwnerID:
    - "286467027705790464" # WavJaby#3673
    - "810822763601461318" # XinShou#0404
    - "270062130470846465" # XinShou#8787
    - "308721713066147840" # 阿正#6176
    - "860182127798124594" # XinShou#1699

  # watching / listening / playing / competing / streaming
  activityMessage:
    - "competing;/help"

  # Youtube API KEY (https:// console.cloud.google.com/apis/)
  apiKey: "AIzaSyA6KoqXbs5ZI2Zqlo-BcUPULQDBe8fVWPw"

  # Will send command used message to console
  debugMode: true


##################################################
################## ID Settings ###################
##################################################

IDSettings:
  guildID: "858672865355890708"
  logChannelID: "858672865816346634"
  authChannelID: "860469251176792065"
  consoleChannelID: "861936727329472512"
  controllerChannelID: "868320517000663120"
  informationChannelID: "858672865444626439"


  botRoleID: "858972360609366037"
  logRoleID: "858672865355890715"
  memberRoleID: "858672865385119757"
  boostedRoleID: "858706338199896084"
  internalRoleID: "865566302773051454"

  adminPermissionID: "858672865444626433"

  # When member join the server will get role(s).
  joinRoleID:
    - "858707058530451476"
    - "858703314606751764"
    - "858701368457953360"
    - "858672865385119755"

  # When member pass the auth can get role(s).
  confirmRoleID:
    - "858672865385119757"
    - "858704345448841226"


##################################################
################ Rooms Settings ##################
##################################################

RoomSettings:
  defaultRoomName: "《🔊》%name% 房間"
  defaultRoomChatName: "《📄》%name% 文字頻道"
  defaultRoomBitrate: 128000

  roomCategoryID:
    - "869925166522716211"


##################################################
############## Services Settings #################
##################################################

ServiceSettings:
  newServiceName: "《❗》%name% 客服"
  defaultServiceMessage: "%reporter% 您好, 請說明您的問題, 工程組將會在不久後聯絡您"

  serviceCategoryID:
    - "864673016653807627"

  serviceTagRoleID:
    - "858672865409630245"


##################################################
################### MutiBot ######################
##################################################

MultiBot:
  tokens:
    - "NjA4MDgwNjE4ODk4ODQ5ODI1.XUi9NQ.K8XYERpv6Lsn5KSv3ORgBXOeUGc" # 犬
    - "ODY3MzEyMzI3MDQ0NjI4NDgw.YPfRjA.pvtrfv3OzDqiLNGz9c_4unX-310" # 狐
    - "Njc5MzMwNzU4MTkxNDgwODY0.XkvyEg.La_10QDAWVoGL0DsuofwUQCpke4" # 螈
    - "NjM1NDc0MDE3MDM3NDUxMjc1.XaxlTA.3HDGP6fzHwaJTwxDqdRdgBq7qis" # 豬
    - "ODY3MzExMjU5NTkzOTk4MzQ3.YPfQjg.X7kJLIEXrjOXLpCm8y75nmjARiQ" # 貓

  randomBot: true
